version: "3.8"

services:
  ros:
    container_name: robot-arm-container
    build:
      context: .
    image: robot-arm-ros
    stdin_open: true
    tty: true
    volumes:
      - ./ros2_ws:/home/dockeruser/ros2_ws
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - TERM=xterm-256color
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
    network_mode: host
